### ISSUE TITLE
Aucun formulaire ne s'affiche

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#1]
Je crée un container People, avec un slug people, et comme modèle : 
`{"people": {"fields": [{"title": "What\'s your name?", name: "ldp_name"}, {"title": "Who are you?", "name": "ldp_description"}]}}`

Quand je crée une ressource, je choisis le container, mais aucun formulaire ne s'affiche.

**Comment by balessan** [comment]
Je viens de tester avec une installation de Worpdress fraîche.
Deux raisons possibles:
- j'ai ajouté le LDP-framework en tant que submodule dans l'application, afin de pouvoir debugger et tester certaines choses, il faut donc exécuter 2 commandes pour récupérer le contenu du sous-module:

`git submodule init`
`git submodule update`

Ces commandes devraient déclencher automatiquement le clonage de LDP-framework dans le répertoire /library/js/. Je les ai ajoutés dans le wiki, page installation (https://github.com/assemblee-virtuelle/wpldp/wiki/Installation)
- il manque un .htaccess définissant les règles de réécriture et permettant ainsi de résoudre la route en /%postname%, ci-dessous la base de .htaccess à utiliser:

`<IfModule mod_rewrite.c>`
`RewriteEngine On`
`RewriteBase /your_site/`
`RewriteRule ^index\.php$ - [L]`
`RewriteCond %{REQUEST_FILENAME} !-f`
`RewriteCond %{REQUEST_FILENAME} !-d`
`RewriteRule . /your_site/index.php [L]`
`</IfModule>`

Confirme-moi si l'une ou l'autre ou les deux solutions combinées te suffisent.

**Comment by sylvainlb** [comment]
C'est quoi un submodule ?

Le 23 novembre 2015 14:31, Benoît Alessandroni notifications@github.com a
écrit :

**Comment by balessan** [comment]
Git te répondra mieux que moi: https://git-scm.com/docs/git-submodule

Ca permet d'ajouter dans des répertoires de tes projets d'autres projets versionés sous git (genre de gestion de dépendances...)

**Comment by balessan** [comment]
Tu ne m'as pas dit si ça résolvait ton problème du coup ?

**Comment by sylvainlb** [comment]
Non. J'ai créé le sous-module, j'ai même recréé un container, mais j'ai
toujours pas de formulaire.
Dans la console, j'ai "mal formé", et quand j'édite mon container, je n'ai
pas de champ en face de "Model editor mode"

2015-11-24 18:15 GMT+01:00 Benoît Alessandroni notifications@github.com:

**Comment by balessan** [comment]
Tu n'as pas oublié les quotes autour de name dans ton modèle ?

```
{"people": {"fields": [{"title": "What is your name?", "name": "ldp_name"}, {"title": "Who are you?", "name": "ldp_description"}]}}
```

Installation de JSONeditor ?

https://github.com/assemblee-virtuelle/wpldp/wiki/Installation 

Voir la dernière section:

```
npm install jsoneditor
```

J'ai du mal à voir ce que ça peut être.

**Comment by balessan** [comment]
Screenshot ou copie du message de la console ?

Screenshot du contenu de ton container ?

**Comment by sylvainlb** [comment]
Il faut faire quelque chose après l'installation de jsoneditor pour qu'il
soit pris en compte ?
Sinon même avec un copier-coller de ton modèle ça ne fonctionne pas.
Il faudrait que j'essaye avec une install fraiche de wordpress pour voir si
ça vient de mes anciens développements.

Le 6 janvier 2016 à 22:05, Benoît Alessandroni notifications@github.com a
écrit :

**Comment by sylvainlb** [comment]
[image: Images intégrées 1]

Cette fois dans la console j'ai "ReferenceError: MyStore is not defined"
Pas sûr de pourquoi le message a changé.

2016-01-06 22:10 GMT+01:00 Benoît Alessandroni notifications@github.com:

**Comment by balessan** [comment]
Je ne vois pas l'image (dommage github)

Tu n'as pas une autre erreur avant celle-là ?

**Comment by sylvainlb** [comment]
Oui je t'ai mis en copie pour que tu aies l'image.
J'ai créé un lien symbolique de mon plugin dans /var/www pour que le
fichier js soit accessible et ça fonctionne. Mais je ne comprends pas
pourquoi je dois faire ça. Il n'y a pas une manière plus orthodoxe de
rendre les fichiers de plugins accessibles au client ?

2016-01-06 22:26 GMT+01:00 Benoît Alessandroni notifications@github.com:

**Comment by balessan** [comment]
Qu'est-ce que tu entends par 

```
rendre les fichiers de plugins accessibles au client ?
```

C'est quoi ta structure ?
Ton wordpress est dans /var/www/ ou pas du tout ?
Le lien il pointe précisément de quoi vers quoi ?

**Comment by sylvainlb** [comment]
Tu as raté mes mails :)
Mon wordpress est installé dans  /srv/www/wp-content/localhost, et le tout
est branché sur /var/www avec un système de liens symboliques. Je sais pas
trop pourquoi, c'était l'installation par défaut. Du coup, quand j'ai créé
et installé le module, ses fichiers n'étaient pas accessibles au client,
parce que pas dans /var/www.
Peut-être que c'est à l'installation du plugin qu'il aurait du copier les
fichiers.

Mon lien pointe de /var/www vers ~/wpldp où j'ai installé le plugin

Le 6 janvier 2016 à 22:32, Benoît Alessandroni notifications@github.com a
écrit :

**Comment by balessan** [comment]
Super weird tout de même. C'est vrai que j'ai toujours installé mes wordpress dans /var/www/...
Une histoire de droit alors ?

Je ne comprends pas non plus pourquoi tu dois faire ça...

**Comment by balessan** [comment]
Mais c'est réglé ?

**Comment by sylvainlb** [comment]
pour mon cas oui. Mais on risque de se retrouver avec d'autres personnes
qui ont le même souci. Je vais réessayer une installation à neuf pour voir.

2016-01-06 22:44 GMT+01:00 Benoît Alessandroni notifications@github.com:

**Comment by balessan** [comment]
Pour information j'ai déjà déployé le plugin sur le site de l'AV, celui de Practishare et le mien, et je n'avais pas rencontré de problèmes particuliers.

Le problème réside là (ligne 270 de wpldp.php):

```
plugins_url('library/js/LDP-framework/mystore.js', __FILE__),
```

Si l'utilisateur courant n'a pas les bons droits sur le répertoire ou se trouve le plugin, ça va forcément coincer...

**Comment by sylvainlb** [comment]
Ok, c'est peut-être lié à la manière dont j'ai installé le plugin, puisque
je l'ai créé directement.

Le 7 janvier 2016 à 11:27, Benoît Alessandroni notifications@github.com a
écrit :
