### ISSUE TITLE
Les données description ne s'affichent pas quand je "post"

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/wpldp#11]
J'ai seulement rempli les données description d'une idée (PAIR à PAIR), je ne sais donc pas ce qu'il en est des autres champs ...

**Comment by balessan** [comment]
Lien vers la ressource ?

**Comment by GuillaumeAV** [comment]
http://www.virtual-assembly.org/wp-admin/post.php?post=2730&action=edit&message=4
Au fait, il faut que j'appuie sur publish après ?

**Comment by balessan** [comment]
Bah je les ai moi les données...

Et non normalement le "Post" suffit, si ta ressource est déjà publiée.
