### ISSUE TITLE
Le champ description apparait 2 fois 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/wpldp#12]
Il y a un premier champ "Idea description" puis un 2ème champ "Description". un seul suffit je pense, à moins qu'on spécifie par exemple, description courte avec une limite de caractères et description longue ...

**Comment by balessan** [comment]
Attention ça ce n'est pas un bug, c'est un problème de modèle. Il faut modifier le container Idea associé ici: 

http://www.virtual-assembly.org/wp-admin/edit-tags.php?action=edit&taxonomy=ldp_container&tag_ID=25&post_type=ldp_resource

Il faut distinguer les problèmes de conception des modèles des problèmes de fonctionnement, même si la barrière est fine ;-)
