### ISSUE TITLE
Normaliser les champs date de naissance etc. 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/wpldp#15]
histoire de pouvoir les expoiter ensuite, mais ce n'est pas urgent ;-)

**Comment by sylvainlb** [comment]
Ça veut dire quoi normaliser ?

**Comment by balessan** [comment]
Ne pouvoir saisir que YYYY-MM-DD ? Quitte a avoir un petit calendrier ?

**Comment by sylvainlb** [comment]
Ok, compris. Du coup des champs de type date, avec webshins ?

**Comment by balessan** [comment]
Par exemple :-)

**Comment by balessan** [comment]
Webshims, genre ça: https://afarkas.github.io/webshim/demos/ ? Je ne connaissais pas du tout ;-)
J'adore l'open-source pour découvrir des trucs !

**Comment by sylvainlb** [comment]
Le principe de webshims/polyfill est de boucher les trous de support html5. En l'occurence les <input type="date"> sont encore assez mal supportés, mais sont en train de devenir un standard (enfin débarassés des datepickers!).

**Comment by Septentrion** [comment]
Hello boyz ! Je fais un petit tour d'horizon des trucs en suspens dans le plugin. Apparemment, **webshim** ne serait plus maintenu (sauf bugs critiques), est-ce une bonne voie ? Pourquoi pas simplement jQuery UI ?

**Comment by balessan** [comment]
Champ date remplace par jquery datepicker (on sortira de jquery plus tard).

Voir commit 8f295d3febf9cf68f96221e1afaef797077b99ff
