### ISSUE TITLE
Propriétés projets : Un github ou une URL serait bienvenus

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/wpldp#17]
Un champ URL dans un premier temps pour tout à fait convenir !

**Comment by sylvainlb** [comment]
Je dirais un github ET une url.
Et une image

**Comment by sylvainlb** [comment]
Cela dit cette issue devrait être sur l'ontologie PAIR, et pas sur wpldp

**Comment by balessan** [comment]
Elle date du 5 decembre et je confirme que comme elle porte sur le modèle de donnée elle n'a pas sa place ici ;-)

**Comment by sylvainlb** [comment]
Du coup on ferme toutes les issues relatives aux données ?

**Comment by balessan** [comment]
Faisons du ménage ! De toute façon, je reviendrais dessus en direct avec Guillaume la semaine prochaine.
