### ISSUE TITLE
L'éditeur de modèle ne fonctionne pas

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#19]
Aucun champ n'apparait dans le formulaire. J'imagine que j'aurais du installer json-editor, mais la procédure d'installation ne fonctionne alors pas.

**Comment by balessan** [comment]
Voir le wiki: https://github.com/assemblee-virtuelle/wpldp/wiki/Installation

> Next step, getting the JSONEditor library we use. First, go to the library/js folder
> cd library/js
> 'From the plugin directory
> Then you can install the project using NPM or Bower:
> npm install jsoneditor
> or
> bower install jsoneditor

Pas suffisant ?

**Comment by sylvainlb** [comment]
json editor n'était pas installé, npm n'était pas disponible sur le serveur, il a fallu l'installer à la main.
