### ISSUE TITLE
Possibilité de choisir le contexte

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#2]
Il faudrait pouvoir choisir quel contexte json-ld utiliser pour les ressources de l'api.

**Comment by balessan** [comment]
Fait, voir commit : https://github.com/assemblee-virtuelle/wpldp/commit/7c2a7169ddb8ba0a6cd43dcef181caed3ee230ec

S'assurer d'utiliser un contexte publié en ligne, sinon ça éclate.
