### ISSUE TITLE
Faciliter la mise en place du plugin

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#21]
Il faudrait un plugin packagé, zippé, potentiellement présent dans la bibliothèque wordpress.
La nécessité du préfixe _ldp des champs n'est pas indiquée. Aucune aide n'est donnée pour créer un modèle. On ne sait pas au départ qu'on peut créer les modèles PAIR.

**Comment by balessan** [comment]
Faut documenter quoi.

Après je ne suis pas sûr que la modification des modèles se veuille accessible à tous... Mais pour le coup du préfixe vaut mieux le préciser effectivement. 

Aucune idée de comment donner de l'info facilement à l'utilisateur par contre.

**Comment by sylvainlb** [comment]
Le problème est que pour l'instant quand on installe le plugin on ne peut
rien faire, c'est pas franchement intuitif.
Je pense qu'il faut qu'on travaille à simplifier l'usage.

**Comment by balessan** [comment]
Ah mais ça on est d'accord.
First step: You can find a packaged version of the plugin in 1.0.0 version here: 
http://www.virtual-assembly.org/projects/

Direct download link: http://www.virtual-assembly.org/wp-content/uploads/2016/03/wpldp.tar.gz

**Comment by sylvainlb** [comment]
C'est bon ça !
Un zip ne serait pas plus facile pour les users?

**Comment by balessan** [comment]
J'y ai pensé mais je n'ai pas trouvé la commande de conversion...

**Comment by sylvainlb** [comment]
Le fichier est compressé automatiquement quand on met à jour github ?

**Comment by balessan** [comment]
Nope, faut pas rêver encore ;-) C'est un instantané du début de la semaine.
Si c'est faisable ça peut être cool par contre !

**Comment by sylvainlb** [comment]
Ah ok, j'étais impressionné ;)
Ça doit être faisable, mais git ne donne que des hooks web, donc il faut monter un serveur web pour ça.

Le mieux est que @Tymk nous monte un serveur alternatif à github et qu'on mette un hook directement sur le git :)

**Comment by plup** [comment]
@sylvainlb : Je veux bien le faire mais il me semble qu'on s'était dit de ne pas éparpiller les efforts et donc de commencer par valider l'avenir de Slack avant de poursuivre. 
Après s'il y a urgence sur Gitorious, il suffit de me le dire et j'essaie detrouver un peu de temps pour ça.

**Comment by balessan** [comment]
Non il n'y a pas du tout urgence...

Le 24 mars 2016 à 16:21, Plup notifications@github.com a écrit :

> @sylvainlb https://github.com/sylvainlb : Je veux bien le faire mais il
> me semble qu'on s'était dit de ne pas éparpiller les efforts et donc de
> commencer par valider l'avenir de Slack avant de poursuivre.
> Après s'il y a urgence sur Gitorious, il suffit de me le dire et j'essaie
> detrouver un peu de temps pour ça.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/assemblee-virtuelle/wpldp/issues/21#issuecomment-200883820

## 

Benoît ALESSANDRONI

_Web developer / développeur Web_
Tél: 06 35 51 64 64

**Comment by sylvainlb** [comment]
Pas d'urgence, juste une justification supplémentaire de tes idées !

**Comment by balessan** [comment]
Plugin présent dans le magasin de wordpress, considéré comme closé: https://wordpress.org/plugins/wp-ldp/
