### ISSUE TITLE
Entrée dans le formulaire ne l'enregistre pas

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#22]
Appuyer sur Entrée dans le formulaire effectue la mauvaise action et le formulaire n'est pas enregistré.

**Comment by balessan** [comment]
Done. See commit f8f802a5f5ba0418722154c29570fcb47dd46758

**Comment by balessan** [comment]
Bizarre car chez-moi les deux boutons font la même chose.

**Comment by sylvainlb** [comment]
Je retesterai chez moi
