### ISSUE TITLE
Rendre plus évident de choisir un container quand on crée une ressource

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#23]
Quand on crée une ressource il faut aller choisir le container, mais ce choix n'est pas très visible, loin en bas à droite. Il faudrait le rendre plus visible.

**Comment by balessan** [comment]
Suggestion ? Mettre ça au milieu avant le formulaire ? Pas sûr qu'on puisse customizer ça vraiment comme on le veut, mais je vais voir

**Comment by sylvainlb** [comment]
Effectivement déplacer la boite serait le mieux. Ça peut se faire avec un gros hack css, mais il y a peut-être d'autres solutions

**Comment by balessan** [comment]
La meta box a été déplacé au milieu, au dessus du formulaire de saisie. Enough ?

See commit 3f0899fcf50f4753bcd96d5561edda6aabfbb104

**Comment by sylvainlb** [comment]
Je ne vois pas la différence... C'est moi le bug ?

**Comment by balessan** [comment]
Non c'est que tu as pullé avant la pull request qui intégrait ça.

**Comment by sylvainlb** [comment]
Ah ok. Je change de remote.

**Comment by sylvainlb** [comment]
Nice!
