### ISSUE TITLE
Ajouter un média directement depuis le formulaire de création de ressource

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#25]

**Comment by balessan** [comment]
Est-ce que la solution d'ajouter dans la sidebar une possibilité d'uploader le média direct convient ?

Ou il faut transformer le champ input en champ d'upload ? (pas sûr que 2 soit faisable, vu que le formulaire vient de ldp-framework).

J'aurais tendance à partir sur 1, un avis ?

**Comment by balessan** [comment]
Voir ceci: http://wordpress.stackexchange.com/questions/4307/how-can-i-add-an-image-upload-field-directly-to-a-custom-write-panel

**Comment by sylvainlb** [comment]
Oui, le 2 parait excessivement compliqué, étant donné qu'on est parti sur une génération de formulaire hors wordpress.
Le 1 me parait bien suffisant, au moins dans un premier temps. L'important est que les choses soient bien expliquées pour que les utilisateurs comprennent comment s'en servir.

**Comment by sylvainlb** [comment]
J'ai pas tout lu, mais ça avait l'air compliqué ! :-p

**Comment by balessan** [comment]
Done, the easy way ;-) See those links for reference: 
- http://wordpress.stackexchange.com/questions/17723/how-do-i-add-media-to-a-custom-post-type
- http://www.webmaster-source.com/2013/02/06/using-the-wordpress-3-5-media-uploader-in-your-plugin-or-theme/

And see commit 45226df68576b9fe4ab807e86bac908629b63efa for the actual code
