### ISSUE TITLE
Proposer une entrée par container dans le menu

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#28]

**Comment by balessan** [comment]
Il faut investiguer l'action add_submenu_page, qui doit être déclenchée dans le menu_init en fonction de la récuperation des containers via get_terms('ldp_container').

Voir:
https://developer.wordpress.org/reference/functions/add_submenu_page/
http://stackoverflow.com/questions/21284919/how-to-create-wordpress-dashboard-sub-menu-pages-dynamically
http://wordpress.stackexchange.com/questions/195623/dynamic-admin-submenu

C'est un genre de pense-bête ;-)

**Comment by sylvainlb** [comment]
Ça me parait pas si bête que ça !

**Comment by balessan** [comment]
Done avec un bemol, l'apparition des menus par container fait disparait le menu 'Add a resource'. Je ne comprends pas pourquoi right now. Y revenir plus tard ?

See commit cb146a5a4cb2a8059ae9a8a7193e13ffed0aea21
