### ISSUE TITLE
Editeur de modèle

### ISSUE THREAD

**Issue by sylvainlb** [assemblee-virtuelle/wpldp#3]
Définir un modèle dans un textarea n'est pas commode. Ce serait bien d'avoir un éditeur avec une interface plus riche pour définir un modèle.

**Comment by balessan** [comment]
Work in progress en intégrant via NPM la librairie : https://github.com/josdejong/jsoneditor

L'aspect display est correct, la sauvegarde déconne pour le moment !

**Comment by balessan** [comment]
Done: see commit https://github.com/assemblee-virtuelle/wpldp/commit/6159c0cb0209d42b4de0c01cdb3db6e77ca15e88 and the previous ones.
