### ISSUE TITLE
Add API endpoints for retrieving the list of sites a site knows 

### ISSUE THREAD

**Issue by balessan** [assemblee-virtuelle/wpldp#32]
When you connect to the network, you should be able to connect to some default sites, and retrieve the list of sites they know so that you will be able to request data from.

See linked data fragments:
- http://linkeddatafragments.org/

**Comment by balessan** [comment]
Thanks to the new Wordpress Rest API ( https://developer.wordpress.org/rest-api/ ), it should be quite easy...

**Comment by SebLemoine** [comment]
Je ne comprend pas comment utiliser les taxonomies

**Comment by balessan** [comment]
As-tu une question plus précise ?

Le premier objectif est d'avoir une entrée "Sites" dans ton tableau de bord et de pouvoir créer, modifier et supprimer des sites. Ces objets sites n'auront qu'un nom et une description

La deuxième étape est d'ajouter un champ URL sur ces sites ( voir ce tuto: https://pippinsplugins.com/adding-custom-meta-fields-to-taxonomies/ , ou s'inspirer de ce que je fais pour les champs ldp_model de la taxonomie ldp_container par exemple )

La 3ème étape est d'utiliser cette taxonomie à l'activation du plugin ou à la création d'une nouvelle entrée de type projets, ressources, etc dans le back-office ( morceau beaucoup plus gros ). Quand je dis utiliser j'entends:
- lors de la création d'un lien vers une autre ressource dont on copie l'URL, vérifier si on connait déjà cette url dans notre liste de sites
- si ce n'est pas le cas, créer une nouvelle entrée site avec comme url la base de l'url du site: http://monsite.com/

Encore mieux par la suite:
- permettre dans le back-office la recherche des ressources auxquelles s'affilier via un appel aux sites qu'on connait lors de l'auto-complétion ( auto-complétion qui n'existe pas encore ) permettant de sélectionner les projets, les gens auxquels se rattacher. Par exemple si on cible un objet de type person, appeler de manière concurrente les urls /ldp/person de la liste des sites connus, afin de pouvoir rechercher dans cette liste agrégée de sources multiples de personnes. Si pas clair on en parle demain

**Comment by SebLemoine** [comment]
Ok ! merci pour les étapes ;) Je découperai les commit avec ces étapes

**Comment by balessan** [comment]
Pour précision, les points 1 et 2 évoqués dans le commentaire précédent:

> lors de la création d'un lien vers une autre ressource dont on copie l'URL, vérifier si on connait déjà cette url dans notre liste de sites
    si ce n'est pas le cas, créer une nouvelle entrée site avec comme url la base de l'url du site: http://monsite.com/

Son plutôt liés au ticket suivant: https://github.com/assemblee-virtuelle/wp-ldp/issues/30

**Comment by SebLemoine** [comment]
2 first step done for the admin part ! see commit : 1082d819dcf3fb3c11af5bc0b514f8c63281e96b
i will create a view who when we click on show in admin for a web site : we show the detail of number of ressource he have ( at the URL myWebSite/ldp )

**Comment by balessan** [comment]
Nice ! Je te mets des remarques dans le commit.

**Comment by SebLemoine** [comment]
Je pense qu'il y a un problème au save car je n'arrive pas a retrouver après ou sont stocker les infos

**Comment by balessan** [comment]
Les infos ( pour le champ URL ) doivent être stockés dans la table wp_term_meta dans la base. Les infos de base ( nom du site et description ) dans la table wp_term

**Comment by SebLemoine** [comment]
Elles sont stockés dans wp_option pour le moment. je vais corriger !

**Comment by balessan** [comment]
Je sais pourquoi, la méthode que j'ai utilisé pour gérer mes champs perso était ancienne, l'ajout de la table wp_term_meta est assez récente et on ferait mieux de se recaller dessus (avant on mettait tout dans wp_option). Utiliser : update_term_meta au lieu de update_option

La possibilité de créer des term_meta date de la 4.4.0, j'ai démarré le projet en 4.3 et des brouettes...

**Comment by SebLemoine** [comment]
Ok !

**Comment by balessan** [comment]
I do close this one as the goal is reached and the issue #65 contains the missing feature definition.
