### ISSUE TITLE
Message "Cannot redeclare class WpLdp\WpLdp"

### ISSUE THREAD

**Issue by Septentrion** [assemblee-virtuelle/wpldp#35]
J'ai essayé d'installer le plugin sur une instance de Wordpress 4.4.4, en déplaçant simplement les fichiers via ftp, et lorsque je demande à l'activer, j'obtiens ce message.

Je peux quand même accéder à la page d'options, mais je ne sais pas si le plugin est complètement fonctionnel malgré tout (je n'ai pas d'autre menu, par exemple)

![capture d ecran 2016-08-10 a 12 01 37](https://cloud.githubusercontent.com/assets/1136883/17549791/4bbf2762-5ef2-11e6-915c-360343ea5504.png)

**Comment by balessan** [comment]
Ma faute, j'ai commité l'ajout d'un namespace hier sans tester (ceci dit tu as accès au menu Ressources quand même) ;-)

**Comment by balessan** [comment]
As tu suivi le process d'installation ? Si tu as cloné les fichiers depuis github il y a quelques trucs à installer à la main. Voir le [wiki d'install](https://github.com/assemblee-virtuelle/wpldp/wiki/Installation)

**Comment by balessan** [comment]
Je viens de commiter un fix, testé chez moi. Tu peux récupérer cette version et désactiver/réactiver pour tester ? Voir commit 6fe0eb1cecdf85daacf286546d906dec36b8dbfd

**Comment by Septentrion** [comment]
OK, je vais tester.
Je n'avais pas lu la doc d'installation ;o) donc les submodules ne sont pas intégrés.
Retour d'expérience un peu plus tard
