### ISSUE TITLE
[From: Michel] Suite de #35 : 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/wpldp#37]
Hello Benoît !
Très bonne nouvelle d'avoir le plugin à disposition dans le magasin. J'ai réessayé d'installer le plugin avec cette méthode , mais ça ne fonctionne pas vraiment mieux.
Le fait d'avoir ôté l'espace de noms a simplement changé l'erreur : WpLdp au lieu de WpLdp\WpLdp :o)
Je vais refaire une tentative sur un WordPress "neuf" . Sur mon installation de test, j'avais diverses autres extensions en service.
A bientôt

**Comment by balessan** [comment]
Salut Michel !

Tu es sur que tu n'as pas déjà le plugin d'installé ? Ou un code qui contiendrait déjà une classe s'appelant WpLdp ? Peux-tu tester en désactivant préventivement toutes les autres extensions installés et en activant seulement celle-là ? Il faudrait qu'on se voit pour que je regarde car ça m'intrigue vraiment...

**Comment by Septentrion** [comment]
Hello Benoît,

Je viens de refaire l'installation depuis zéro : un nouveau WordPress (4.6) + le plugin depuis le magasin WP.  Ça s'installe sans problème, mais maintenant, si je veux ajouter une ressource, j'ai une page vide (cf. capture). Bizarre, non ? — mais, de fait, je n'ai pas suivi la procédure du wiki.

Si tu veux regarder, l'URL : [](http://peirce.sens-commun.org/wpldp)
Les identifiants de connexion : admin/wpldp

![capture d ecran 2016-08-19 a 18 56 30](https://cloud.githubusercontent.com/assets/1136883/17817512/318542ce-663f-11e6-8bec-e5f774faf9fc.png)

**Comment by balessan** [comment]
Jusque là c'est normal, les containers PAIRs ne sont pas initialisés. Voir [wiki  pour la première utilisation](https://github.com/assemblee-virtuelle/wpldp/wiki/The-first-usage)

**Comment by balessan** [comment]
Au delà de ça, j'ai réglé un bug critique et poussé une MAJ via Wordpress. Si tu peux mettre à jour et retester après être allé dans Settings > WP-LDP Settings et avoir coché et valider "Initialize the PAIRs containers" ce serait super @Septentrion !
