### ISSUE TITLE
Permettre autocomplétion DBpedia sur thèmes et compétences 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/wpldp#40]
Afin de permettre aux uttilisateurs de linker des URI uniques ...

**Comment by balessan** [comment]
Ajouter le support de Select 2 pour l'aspect requête et affichage plus propre, en mode multi select.

Plutôt que cibler DBPedia, cibler une instance de référence Semantic Forms et y appeler une URL qui retouner les résultats DBPedia + résultats d'instance WPLDP crawlé.

**Comment by SebLemoine** [comment]
Le script utilisé sur sf pour la complétion DBPedia a été adapté pour WP. Il fonctionne mais je ne trouve pas le moyen de le mettre en place a la génération du formulaire  ( exemple : le champ compétences doit avoir la classe "hasLookup" et je ne sais pas comment la rajouter uniquement pour ce champ ) see 6c8ef0735800822d874c890d1a79aeac9b216120

**Comment by balessan** [comment]
La SOC ( https://en.wikipedia.org/wiki/Separation_of_concerns ) est mal faite du côté Javascript. À l'heure actuelle, c'est au sein de l'objet MyStore, qui provient de l'injection de la librarie ldpframework ( for ici: https://github.com/assemblee-virtuelle/LDP-framework/blob/774bc4e0f05fc3788c5090b6c44abcc4f9686b5b/ldpstore.js ) que la génération du formulaire est géré. Il faudrait sortir ce code là de cette libraire et en faire un javascript indépendant, injecté dans le plugin. 

Gros travail de refonte, si ça botte l'un d'entre vous c'est cool ! (et c'est du pur JS)

**Comment by balessan** [comment]
Done.
See commit abfabd31620692c82f9b1697267c9a572dbe33ce
We will have to force the refresh of all models after json completion.
