### ISSUE TITLE
Synchroniser l'apparition des champs et la sélection du container

### ISSUE THREAD

**Issue by balessan** [assemblee-virtuelle/wpldp#5]
Lorsqu'on change de container, modifier directement les champs présents.

**Comment by sylvainlb** [comment]
Ah je comprenais pas le sens de cette phrase :)

**Comment by balessan** [comment]
Pouvoir changer de container à la volée sous-entend de pré-charger les modèles correspondants à chaque container dans la page. C'est pas un peu lourd ?

**Comment by balessan** [comment]
Utilisation de la REST Json API sinon... Je teste.

**Comment by balessan** [comment]
Bon la JSON Rest API officielle est déployée via l'installation de JetPack. Si on ne veut pas de dépendances, il faut s'implémenter un petit endpoint maison. Je teste ça !
wpldp-ajax.php ongoing.

Encore un truc découvert, comment réaliser des calls AJAX sur du contenu WP ;-)

**Comment by sylvainlb** [comment]
On peut pas recharger la page automatiquement quand on a choisi un container ?

**Comment by balessan** [comment]
Recharger ne suffit pas il faut sauvegarder l'information. 
Poster sur post.php la donnée tirée du formulaire ça devrait fonctionner. 
Plus simple effectivement. Je vais tester.

**Comment by balessan** [comment]
Suffit de soumettre le formulaire quoi. Purée comment je suis parti loin pour rien !

**Comment by balessan** [comment]
Ca fonctionne en soumettant brutalement le formulaire, mais idéalement faudrait passer par un call AJAX ce serait plus propre non ? Pas de reload de la page juste un refresh du formulaire.

**Comment by balessan** [comment]
Done. See commit 7d764109f73888e1454ff371eb4e3d7ed833d34e

**Comment by sylvainlb** [comment]
Dans l'absolu ça serait plus propre, mais je pense qu'il y a des trucs plus impropres à rendre propres avant :)
