### ISSUE TITLE
404 errors on multisite installation

### ISSUE THREAD

**Issue by MaiaDereva** [assemblee-virtuelle/wpldp#50]
On a multisite Wordpress installation, even if Permalinks are reinitialized, there is still a 404 error when displaying Ressources

**Comment by balessan** [comment]
Alert: Critical one

**Comment by davixin** [comment]
Salut, j'ai aussi une erreur "404 - Page Not Found" en essayant d'utiliser le plugin sur mon site wordpress qui a une installation multisite,
merci ! :)

**Comment by balessan** [comment]
Fixed by 480790cfa09f69e2e1cbd50eee8e70fcac280764 , update will be released soon
