### ISSUE TITLE
Pas de label pour les formulaires

### ISSUE THREAD

**Issue by Septentrion** [assemblee-virtuelle/wpldp#51]
Je viens de faire la mise à jour du plugin (v1.0.11). Je suis repassé par la case **Settings** pour avoir les bons conteneurs, mais...

Lorsque je veux créer un acteur (moi, au hasard :o) le formulaire s'affiche sans les labels.

![capture d ecran 2016-09-23 a 15 36 10](https://cloud.githubusercontent.com/assets/1136883/18787667/193e8e8e-81a4-11e6-940d-a764e0d43fe2.png)

**Comment by Septentrion** [comment]
Bon... Réglé miraculeusement à la seconde tentative, manifestement :o)

**Comment by balessan** [comment]
Closed because unable to reproduce.
