### ISSUE TITLE
Vérifier le listage des répertoires

### ISSUE THREAD

**Issue by balessan** [assemblee-virtuelle/wpldp#63]
Lorsqu'on appelle le répertoire /ldp à la racine d'un site, on devrait pouvoir lister les différents sous-dossiers présents: dossier person / document / project etc...

Ceci afin qu'un hub de référence ( et autorisé ) puisse crawler les infos.

**Comment by SebLemoine** [comment]
première version où l'on a le nombre de person,orga etc.. créer sans la liste des id.

**Comment by balessan** [comment]
Numéro de commit please @SebLemoine ?

**Comment by SebLemoine** [comment]
SebLemoine@3ac765f

**Comment by balessan** [comment]
Tu as ajouté les ids ? ça se présente comment le résultat en sortie ? Si tu me montres on pourra probablement fermer ce ticket :-)

**Comment by balessan** [comment]
Le service existe, je considère cette issue résolue pour le moment.
