### ISSUE TITLE
Jveux bien aider mais ...

### ISSUE THREAD

**Issue by corbane** [assemblee-virtuelle/wpldp#71]
Bonjour, Guillaume m’expliqua qu’avant-hier vous aviez fait une démo trop bien donc cela m’a motivé à repasser sur le GitHub ! 😊

Mais je me demande si ce trouve sur le dépôt la dernière version a jour ? car il y a des choses comme ceci :

![image](https://user-images.githubusercontent.com/8430545/28169957-29ccf3d6-67e4-11e7-8947-0ccc902ad66e.png)

(visiblement une faute de frappe)

Et côté UI, il y a quelques mois j'arrivais à entrer des Personnes, Idées, etc, aujourd'hui il n'affiche plus rien lors de la sélection du type de ressource.

![image](https://user-images.githubusercontent.com/8430545/28170130-ad2fc384-67e4-11e7-9eaf-64c9a270df5e.png)

Voilà est-ce que je suis en présence de la dernière version auquel cas c top et j’essayerais au mieux de participer.

**Comment by corbane** [comment]
Dernière petit chose, mais là je sais que cela va être plus difficile. L’anglais sur github pour un geek est ce que la barbe est à l’hipster mais vous n’y êtes pas encore à l’international (dsl), y a encore un peu de temps, pour le moment l’initiation est en France donc si sur les issues on pouvait communiquer avec la langue commune ici ça permettre à des gens comme moi de contribuer… pour dire il y a pas que moi qui a du mal avec votre anglais, même google traduction galère 😊 (blague hein ! Surtout j'avoue ce n’est pas tout à fait vrai)

**Comment by GuillaumeAV** [comment]
Helloo :-) Qui se cache donc derrière ce pseudo, je rencontre décidément un peu trop de gens en ce moment :-) J'opterais pour .. Jean-Marie ?
Trop cool que tu sois motivé pour contribuer, je laisse benoit répondre à tes questions .. Cela dit, sur la dernière, il se trouve que plusieurs communautés à l'international font des choses similaires / complémentaires et qu'on prévoit de les (re)contacter pour travailler ensemble ... D'où l'utilisation de l'anglais ..

**Comment by corbane** [comment]
Pfff bande de geek ! 😊  mais je m’en doutais, j’ai essayé ! 😊
Euh oui c’est JM.
Alors j’ai une autre question pour benoit juste pour que je comprenne.
Vous avez converti un ancien code wordpress écrit avec ces fonctions (the_post, post_id) en un code écrit avec les classes WP (WP_Post, etc) ?
Donc il n’est pas impossible de retrouver des ancienne fonction WP collé comme propriété au nouvelle classe WP ?

![image](https://user-images.githubusercontent.com/8430545/28171610-46f304c8-67e9-11e7-9165-00975e52d3fc.png)

**Comment by balessan** [comment]
Salut @corbane 

Effectivement pour le bien du projet et pour pouvoir enclencher la discussion sur de bonnes bases avec les communautés de SoLiD et des plugins Wp-linked-data, lh-rdf ou encore Indie-Web, j'aime autant documenter en anglais.

De plus, j'ai dans le passé travaillé deux ans et demi au Canada et je suis sûr que mon anglais est compréhensible ( même si toujours perfectible ).

Pour répondre de manière plus constructive :-) : oui le code a subi une grosse refonte dans les 2 dernières semaines, en passant d'une architecture bancale à base d'injection de templates utilisant la Loop à une architecture standard basée sur la WP Rest API. Il reste cependant des morceaux de code non nettoyés, ou rétro-compatibles de fait (je pense à ton deuxième snippet qui, lui, fonctionne correctement)

Si tu as seulement fait un clone du github, il te manque probablement le:

```
git submodule init
git submodule update
```

Qui permet normalement de récupérer une version stable du framework JS en charge de la construction du formulaire. N'hésite pas à regarder dans ta console pour savoir ce qu'il se passe. Il y a une doc d'install ici: https://github.com/assemblee-virtuelle/wp-ldp/wiki/Installation ( a priori à jour )

A ta dispo pour plus de précisions, et si tu veux qu'on prenne un temps de bootstrap sur la contribution dans le projet ;-)

++

**Comment by corbane** [comment]
Salut ! 

Il n’y a pas de soucis ! Et non non je ne doute pas de ton anglais, c’est du mien que je doute grave ! du coup je tentais, tu dois imaginer le nombre de doc en anglais que je me farci alors que je n’aime pas… Tu vois dans l’idée, j’ai une demi-mole à chaque fois que je consulte la doc de PHP, houhou elle est en français, bien écrite, complète avec des exemples, le kiff 😊

Bon, et pour wpldp, c trop compliqué pour moi, déjà parce que je perçois encore mal à quoi doit ressembler l’appli fini (même si je comprends à quoi sert les Linked Data). Et aussi parce que le code source est trop compliqué pour moi, il y en a partout, je n’arrive pas à comprendre qui fait quoi et quoi va où ça dépasse mes capacités de petit bidouilleur…:/ (oui j’ai vu par la suite que c’était le Framework js qui manquais)

Mais du coup, je ne suis pas en reste, j’essaie de faire un server de composants riot.js qui ont pour but de former des appli type PWA. j’en aurais besoin pour un site de projet. Evidement j’ai envie de faire simple donc je le fais avec Wordpress (et ça magnifique doc merdique). Alors vu que la génération des formulaires de wpldp n’est pas non plus super sexy ptêtre ça pourras être utile. 

Et oui, je pense que si jamais tu passes au grand voisin faire une démo ou autre et si tu as le temp de m’expliquer tout ce code et l’objectif ça me sera utile pour aider à faire des petits trucs …

JM

**Comment by balessan** [comment]
Cool :-) 

Tu entends quoi par PWA ?

Le code source actuel a été extrèmement simpifié par rapport à ce qui existait précédemment pourtant ;-) Par contre, si tu penses travailler sur de la génération de formulaire en JS ou sur des composants standard d'affichage de Linked Data, c'est cool :-) Ca aurait un lien avec cette issue d'ailleurs: https://github.com/assemblee-virtuelle/wp-ldp/issues/60

Je te pingue quand je passe, tu es sur le Slack de l'AV ou quelque part ou je puisse te rencontrer ?

**Comment by corbane** [comment]
En fait PWA est un nom (plus de com) de google qui expose une méthode de faire des sites à l’aide de techno supporter par peu d’appareil : https://en.wikipedia.org/wiki/Progressive_web_app .
Pour moi il s’agit juste de faire des composants web sachant communiquer uniquement en REST & Ajax et gérer le off line.

Oui pour les schémas j’ai tenté aussi, je suis souvent confrontée au fait de ne pas être dev. Par exemple, je suis passé voir Jean Marc qui m’a expliqué sementic form, j’ai pu voir une magnifique architecture mais en temps qu’utilisateur j’ai pas su quoi en faire. 

Et en temp que de bidouilleur j’avais déjà tenter de le mettre en place sur le WP de mon asso mais impossible pour moi de comprendre où trouver le schéma des schémas justement. Tu vois par ex sur schema.org même s’ils sont trop dance à mon gout pour être humain, au moins je sais quoi, les schémas sont accessibles.

Bref il me faudrait un AV pour les nuls :blush: ! Mal percevoir la finalité concrète (l’interface ui, sont utilisation) et mal percevoir son implantation sont les deux choses qui me freine encore aujourd'hui sur ce projet et oui j’aurais bien besoin d’une mise à niveau.

Oui je suis sur le slack de l’AV (« j-m-v » de mon ptit nom) même si j’y passe rarement. Ton adresse gmail sur github est correcte pour t’envoyer mes coordonnées ? sinon @GuillaumeAV ce fera un plaisir de relayé :wink:

JM

(nb.: Comment on ferme cette issue ?)

**Comment by balessan** [comment]
Je close du coup. On se capte aux grands voisins. Oui mon adresse est correcte sur github.
