### ISSUE TITLE
user interface : not easy to create a profile because of the form ... 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/wpldp#78]
The form only appears when I publish my person profile ... It should appear when clicking on the class ? 

Then, I can't modify it : the form doesn't appear anymore

**Comment by balessan** [comment]
Screenshots of your javascript console please :-)

**Comment by balessan** [comment]
Linked to #77. Fix by commit 94eedb4b2ee994a59910add86257a08d4bc1fda6
