### ISSUE TITLE
Add support of line-breaks in textarea content edition

### ISSUE THREAD

**Issue by balessan** [assemblee-virtuelle/wpldp#8]
When editing a textarea form field content associated with a resource, the line-breaks previously entered are ignored on rendering..

Maybe this issue is more on the LDP-framework side.

**Comment by sylvainlb** [comment]
Not a duplicate of #7 ?

**Comment by balessan** [comment]
Is there a possibility that supporting markdown would solve the issue of properly handling the line breaks ?

I do not see the link there.

**Comment by sylvainlb** [comment]
yes, markdown does support linebreaks. If you replace all textarea by components like pen, you won't have to deal with them anymore. Or else I'm missing something.

**Comment by balessan** [comment]
You're probably right then.

Let's try to close the issue #7 and then check this one...
